# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-28 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_search_id', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('user_query', models.TextField(default='')),
                ('item_data', models.TextField(default='[]')),
                ('final_data', models.TextField(default='[]')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FoodSearchData',
                'verbose_name_plural': 'FoodSearchDatas',
            },
        ),
    ]
