# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-28 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearchApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodsearchdata',
            old_name='final_data',
            new_name='detailed_data',
        ),
    ]
