# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearchApp', '0003_remove_foodsearchdata_detailed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsearchdata',
            name='detailed_data',
            field=models.TextField(default='{}'),
        ),
    ]
